services:
  postgres:
    image: postgres:16-alpine
    env_file: .env
    ports:
      - "5432:5432"
  backend:
    build:
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file: .env
    ports:
      - "8000:8000"
