"""Updated models

Revision ID: 3f032c944999
Revises: 93bd2eb14512
Create Date: 2025-04-20 16:17:17.270161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f032c944999'
down_revision: Union[str, None] = '93bd2eb14512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('task_id', sa.Integer(), nullable=True, default=1))
    op.create_foreign_key(None, 'submission', 'task', ['task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submission', type_='foreignkey')
    op.drop_column('submission', 'task_id')
    # ### end Alembic commands ###
