"""Updated models

Revision ID: 93bd2eb14512
Revises: b2983fd23088
Create Date: 2025-04-20 13:32:48.558219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93bd2eb14512'
down_revision: Union[str, None] = 'b2983fd23088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('submission_attachment_id_fkey', 'submission', type_='foreignkey')
    op.drop_column('submission', 'attachment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('attachment_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('submission_attachment_id_fkey', 'submission', 'attachment', ['attachment_id'], ['id'])
    # ### end Alembic commands ###
