"""Updated models

Revision ID: b2983fd23088
Revises: c6bbab85e24d
Create Date: 2025-04-20 13:28:04.183507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b2983fd23088'
down_revision: Union[str, None] = 'c6bbab85e24d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('attachment', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'attachment')
    # ### end Alembic commands ###
