"""Updated models

Revision ID: c6bbab85e24d
Revises: c9838a670258
Create Date: 2025-04-20 13:13:54.819809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6bbab85e24d'
down_revision: Union[str, None] = 'c9838a670258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attachment', 'owner_id')
    op.drop_column('attachment', 'owner_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachment', sa.Column('owner_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('attachment', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
