"""Updated models

Revision ID: c9838a670258
Revises: efba3f6eeee9
Create Date: 2025-04-20 13:10:08.271387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9838a670258'
down_revision: Union[str, None] = 'efba3f6eeee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachment', sa.Column('task_id', sa.Integer(), nullable=True, default=1))
    op.create_foreign_key(None, 'attachment', 'task', ['task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attachment', type_='foreignkey')
    op.drop_column('attachment', 'task_id')
    # ### end Alembic commands ###
