"""Updated models

Revision ID: efba3f6eeee9
Revises: 6407c58357ea
Create Date: 2025-04-18 13:24:28.940916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efba3f6eeee9'
down_revision: Union[str, None] = '6407c58357ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('event_id', sa.Integer(), nullable=True, default=1))
    op.create_foreign_key(None, 'team', 'event', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team', type_='foreignkey')
    op.drop_column('team', 'event_id')
    # ### end Alembic commands ###
